services:
  my-simple-service:
    image: my-simple-service:1.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-simple-service.rule=Host(`192.168.1.121`)"
      - "traefik.http.routers.my-simple-service.entrypoints=web"
      - "traefik.http.services.my-simple-service.loadbalancer.server.port=8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  typescript-service:
    image: typescript-service:1.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.typescript-service.rule=Host(`typescript.192.168.1.121`)"
      - "traefik.http.routers.typescript-service.entrypoints=web"
      - "traefik.http.services.typescript-service.loadbalancer.server.port=3000"

  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  prometheus:
    image: prom/prometheus:latest

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro

    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro"
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data:
